[project]
name = "accidents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "catboost>=1.2.8",
    "duckdb>=1.2.1",
    "folium>=0.20.0",
    "geopandas>=1.1.2",
    "geopy>=2.4.1",
    "imblearn>=0.0",
    "joblib>=1.5.3",
    "lightgbm>=4.6.0",
    "marimo[recommended]>=0.19.4",
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
    "optuna>=4.7.0",
    "optuna-integration>=4.7.0",
    "osmnx>=2.0.7",
    "pandas>=3.0.0",
    "polars>=1.29.0",
    "pytest>=8.3.5",
    "scikit-learn>=1.8.0",
    "shapely>=2.1.2",
    "xgboost>=3.1.3",
]
